

"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import environ
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"


# Both default to plain localhost so `manage.py runserver` keeps
# working out of the box; set ALLOWED_HOSTS / CSRF_TRUSTED_ORIGINS in
# .eee (comma-separated) to whatever host you actually browse the app
# from - a LAN IP, a custom port, a devcontainer/tunnel URL, a real
# domain - or Django will reject login (DisallowedHost / a CSRF
# "Referer checking failed" error) for anything not listed here.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

# Vite (5173) SPA origin must be trusted for CSRF on credentialed
# cross-origin POSTs directly to Django (no Vite proxy).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000",
    ).split(",")
    if origin.strip()
]
# Always keep local SPA origins even when .env only lists a production host.
for _local_origin in (
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
):
    if _local_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_local_origin)

# Railway (and Render, via RENDER_EXTERNAL_HOSTNAME - same idea) injects
# the domain it just assigned this deploy as an env var, known only
# once Railway generates/attaches it - easy to forget to copy into
# ALLOWED_HOSTS/CSRF_TRUSTED_ORIGINS by hand after the fact, and every
# request (including the platform's own health check) 400s with
# DisallowedHost until someone does. Auto-trusting it removes that
# manual step entirely without weakening anything: this only ever adds
# the exact host Railway itself put this deployment behind, never a
# wildcard. RAILWAY_PRIVATE_DOMAIN (the internal *.railway.internal
# address other services on the project use to reach this one) is
# added to ALLOWED_HOSTS only - it's never browsed to over HTTPS, so it
# has no CSRF origin to trust.
_railway_public_domain = os.getenv("RAILWAY_PUBLIC_DOMAIN", "").strip()
_railway_private_domain = os.getenv("RAILWAY_PRIVATE_DOMAIN", "").strip()

if _railway_public_domain and _railway_public_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_public_domain)

if _railway_private_domain and _railway_private_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_private_domain)

if _railway_public_domain:
    _railway_public_origin = f"https://{_railway_public_domain}"
    if _railway_public_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_railway_public_origin)

# Session/cookie hardening - Secure/SSL-redirect flags are conditioned
# on DEBUG the same way the rest of this file already branches (see
# ALLOWED_HOSTS/CSRF_TRUSTED_ORIGINS above): `manage.py runserver`
# during local dev is plain HTTP, so a hardcoded *_COOKIE_SECURE=True
# would silently break every login/CSRF-protected POST there. A real
# deployment (DEBUG=False) is expected to terminate HTTPS, so these
# flip on automatically without a separate env var to remember to set.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days, if the browser stays open that long

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)

# Railway's own deploy healthcheck prober hits this container's $PORT
# directly (not through the public HTTPS edge that sets
# X-Forwarded-Proto for real browser traffic - see
# SECURE_PROXY_SSL_HEADER below), so request.is_secure() is False for
# that probe specifically even though the app itself is correctly
# deployed behind HTTPS. Without this exemption, SecurityMiddleware
# 301-redirects that plain-HTTP health check to https://.../health/ -
# a redirect Railway's prober does not follow, so it reads as a failed
# check and the deploy never goes healthy. RAG/urls.py's `health/`
# route is the only path that needs this; every real user-facing page
# keeps the normal HTTP->HTTPS redirect.
SECURE_REDIRECT_EXEMPT = [r"^health/?$"]

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# HSTS - tells the browser to remember "always use HTTPS for this host"
# for the given duration, so even a typed/bookmarked http:// URL never
# round-trips over plain HTTP again. Same DEBUG-gated pattern as
# SECURE_SSL_REDIRECT above (a local `manage.py runserver` is plain
# HTTP and must never send this header - a browser that's cached it
# would then refuse to load the dev server at all). Render terminates
# TLS in front of the app and forwards over HTTP internally, same as
# any standard reverse-proxy deployment - SECURE_SSL_REDIRECT still
# works there because Render also sets X-Forwarded-Proto, which
# SECURE_PROXY_SSL_HEADER below tells Django to trust.
SECURE_HSTS_SECONDS = 0 if DEBUG else 60 * 60 * 24 * 30  # 30 days
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Render (like most PaaS hosts) terminates HTTPS at its own edge and
# forwards the request to this app over plain HTTP, setting
# X-Forwarded-Proto to say what the original scheme was - without this,
# Django can't tell the difference between that and a genuine plain-HTTP
# request, so SECURE_SSL_REDIRECT/SESSION_COOKIE_SECURE/CSRF_COOKIE_SECURE
# above would either redirect-loop or never see the request as secure at
# all. Safe to leave set in local dev too: manage.py runserver never
# sends this header, so the condition it checks is simply never true
# there.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # required for pgvector.django.HnswIndex - see ChunkEmbedding.Meta.indexes
    'rest_framework',
    'RAG',
    'corsheaders',
]

# ==========================================
# Django REST Framework (React SPA)
# ==========================================
# SessionAuthentication + CSRF. The SPA calls Django /api/... directly
# (Vite does not proxy). Cross-origin credentialed fetches need CORS
# below + matching CSRF_TRUSTED_ORIGINS. CSRF token is HttpOnly in the
# cookie; JS receives it from GET /api/auth/session/ and sends X-CSRFToken.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT directly from the Django/Gunicorn process with
    # far-future cache headers + gzip/brotli compression - the
    # zero-cost substitute for a CDN/dedicated static host on a
    # single-service free-tier deployment (Render free web service).
    # Placed right after SecurityMiddleware per whitenoise's own docs
    # (before anything that might redirect/modify the response) and
    # before every other middleware in this list, none of which touch
    # static asset requests. Safe to leave installed even in local dev:
    # in DEBUG, STORAGES["staticfiles"] below falls back to Django's
    # plain StaticFilesStorage, so `manage.py runserver` keeps serving
    # static files exactly as it always has (whitenoise no-ops for a
    # path it doesn't recognize as one of its collected files, and
    # runserver's own staticfiles app handler still takes priority for
    # everything else in DEBUG).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'RAG.middleware.RequestTraceMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'RAG.middleware.RoleBasedAccessMiddleware',
    'RAG.middleware.SystemConfigSyncMiddleware',
    'RAG.middleware.RequestActivityMiddleware',
]

# Direct SPA (Vite :5173) → Django (:8000) credentialed CORS.
# Origins must be explicit when CORS_ALLOW_CREDENTIALS is True.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if origin.strip()
]
for _spa_origin in ("http://localhost:5173", "http://127.0.0.1:5173"):
    if _spa_origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_spa_origin)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list({
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
})
CORS_EXPOSE_HEADERS = ["content-type"]
# Prefight cache; safe for local + prod SPA origins above.
CORS_PREFLIGHT_MAX_AGE = 86400

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'RAG.context_processors.sidebar_status',
                'RAG.context_processors.breadcrumbs',
            ],
        },
    },
]
LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "login"
WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Two supported shapes, auto-detected by which env vars are present -
# no separate settings flag to remember to flip per host:
#
# 1. DATABASE_URL (Railway's Postgres plugin - and Heroku-style hosts
#    generally - injects this single connection string, not discrete
#    DB_NAME/DB_USER/... vars under those names). Parsed with
#    django-environ's own env.db(), already a dependency here.
# 2. Discrete DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/DB_PORT (Supabase,
#    Render, local docker-compose - the original shape this project
#    was built around). Used whenever DATABASE_URL isn't set, so every
#    existing deployment/env-file is completely unaffected by this.
#
# Without this, a Railway deploy has no DB_HOST/DB_NAME/... set at all
# (Railway never provisions those exact names), so env("DB_NAME") on
# the discrete path below raises ImproperlyConfigured before the WSGI
# app even finishes importing - the process never binds to $PORT, and
# Railway's health check just times out waiting for a port that was
# never going to open, surfacing as an upstream error with no useful
# stack trace in the deploy logs.
_database_url = env("DATABASE_URL", default="")

if _database_url:
    DATABASES = {"default": env.db("DATABASE_URL")}
    DATABASES["default"]["ENGINE"] = "django.db.backends.postgresql"
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST"),
            "PORT": env("DB_PORT"),
            "CONN_MAX_AGE": 0,
        }
    }

# Without this, Django opens a fresh PostgreSQL connection (full TCP +
# auth handshake) on every single HTTP request and tears it down at the
# end - CONN_MAX_AGE keeps connections open and reused across requests
# instead. CONN_HEALTH_CHECKS (Django 4+) validates a reused connection
# isn't stale before handing it back out, so this stays safe across a
# Postgres restart/network blip rather than just being a raw perf flag.
# Applies to both DATABASES shapes above.
DATABASES["default"]["CONN_MAX_AGE"] = env.int("CONN_MAX_AGE", default=60)
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# Supabase (and most hosted Postgres providers reached over the public
# internet) require SSL on their public endpoint - "prefer" (psycopg2's
# own default) keeps a plain local docker-compose Postgres working
# unchanged, since that one has no SSL configured at all, and also
# keeps a same-project internal connection (Railway's private network
# between services, which isn't TLS-terminated) working unchanged; set
# DB_SSLMODE=require for a public/cross-network Postgres endpoint (see
# DEPLOYMENT.md). env.db() above doesn't populate OPTIONS on its own,
# so this applies the same way regardless of which DATABASES shape was
# selected.
DATABASES["default"].setdefault("OPTIONS", {})["sslmode"] = env("DB_SSLMODE", default="prefer")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# collectstatic's target directory - required for whitenoise (and for
# `manage.py collectstatic` to run at all; it errors without this set).
# Not used by `manage.py runserver` in DEBUG, which serves straight
# from each app's static/ directory instead - see the WhiteNoise
# middleware comment above.
STATIC_ROOT = BASE_DIR / "staticfiles"

# ==========================================
# File storage (free-tier deployment)
# ==========================================
# Document uploads (Document.file, DocumentVersion.file) and profile
# avatars (UserProfile.avatar) go through Django's storage abstraction
# (FileField/ImageField), so which backend is active is entirely a
# settings.py concern - no view/service/model code reads or writes a
# filesystem path directly anywhere in this codebase, and none needs
# to change here either way.
#
# Local dev (and any host with a real persistent disk) keeps the
# original FileSystemStorage default - MEDIA_ROOT above. A free-tier
# host with an EPHEMERAL filesystem (Render's free web service resets
# local disk on every restart/redeploy/scale event) would silently
# lose every uploaded document under that default, so production must
# point at real object storage instead.
#
# USE_S3_STORAGE opts into that: an S3-compatible backend
# (django-storages' S3Storage) pointed at whichever endpoint is
# configured - Supabase Storage (this project's default recommendation,
# since a Supabase project already provides one alongside the Postgres
# database - see DEPLOYMENT.md), Cloudflare R2, Backblaze B2, or real
# AWS S3 are all wire-compatible with the exact same handful of env
# vars, so switching providers later (e.g. onto paid infrastructure) is
# an env var change, not a code change.
USE_S3_STORAGE = env.bool("USE_S3_STORAGE", default=False)

if USE_S3_STORAGE:
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
    # Supabase Storage (and most S3-compatible providers other than AWS
    # itself) serve objects back through the same endpoint host rather
    # than a bucket-subdomain virtual-hosted URL - path-style addressing
    # is what makes AWS_S3_ENDPOINT_URL above actually work as the
    # object base URL.
    AWS_S3_ADDRESSING_STYLE = "path"
    AWS_DEFAULT_ACL = None  # bucket's own access policy decides this - see DEPLOYMENT.md for making the bucket public-read
    AWS_QUERYSTRING_AUTH = False  # public bucket: plain URLs, no expiring-signature query string cluttering every document link
    AWS_S3_FILE_OVERWRITE = False  # matches FileSystemStorage's own default behavior (a same-named upload gets a suffixed filename, never silently clobbers the previous file)

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {
            "BACKEND": (
                "django.contrib.staticfiles.storage.StaticFilesStorage" if DEBUG
                else "whitenoise.storage.CompressedManifestStaticFilesStorage"
            ),
        },
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": (
                "django.contrib.staticfiles.storage.StaticFilesStorage" if DEBUG
                else "whitenoise.storage.CompressedManifestStaticFilesStorage"
            ),
        },
    }

TOP_K = int(os.getenv("TOP_K", 3))

EMBEDDING_MODEL = os.getenv(
    "EMBEDDING_MODEL",
    "all-MiniLM-L6-v2"
)
EMBEDDING_DIMENSION = 384


# ==========================================
# Document Validation
# ==========================================

ALLOWED_FILE_EXTENSIONS = [
    ".pdf",
    ".docx",
    ".txt",
]

MAX_FILE_SIZE = 20 * 1024 * 1024   # 20 MB

# Not env-driven (a stray `CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", 500))`
# used to sit near the top of this file and was unconditionally
# overwritten here two lines later - the env var had zero effect, ever;
# removed rather than fixed, since CHUNK_SIZE stopped being this app's
# real source of truth the moment SystemConfiguration.chunk_size shipped
# (RAG/services/system_config_service.py) - this literal is only the
# seed value get_config() uses the very first time that DB row is
# created, and admin/settings.html is the actual live control from then
# on. CHUNK_OVERLAP is a plain hardcoded constant for the same reason -
# see system_config_service.MANAGED_SETTINGS_FIELDS.
CHUNK_SIZE = 800

CHUNK_OVERLAP = 150

# ==========================================
# Advanced Retrieval (Sprint 6)
# ==========================================
# Query expansion, HyDE, and multi-query retrieval each cost at least
# one extra Gemini call per question on top of the existing hybrid
# pipeline, so they default OFF - flip them on per-deployment via
# .eee once the added latency/cost is acceptable. Metadata filtering
# is opt-in per-call (a `filters=None` param), so it needs no flag.
# Dynamic top-k is local/free (no LLM call) and defaults ON.

ENABLE_QUERY_EXPANSION = os.getenv("ENABLE_QUERY_EXPANSION", "False") == "True"

ENABLE_HYDE = os.getenv("ENABLE_HYDE", "False") == "True"

ENABLE_MULTI_QUERY = os.getenv("ENABLE_MULTI_QUERY", "False") == "True"

ENABLE_DYNAMIC_TOP_K = os.getenv("ENABLE_DYNAMIC_TOP_K", "True") == "True"

DYNAMIC_TOP_K_MAX = int(os.getenv("DYNAMIC_TOP_K_MAX", 10))

MULTI_QUERY_VARIANTS = int(os.getenv("MULTI_QUERY_VARIANTS", 3))

# ==========================================
# Reranking (Sprint 7)
# ==========================================
# BGE Reranker re-scores merged candidate chunks with a cross-encoder
# pass over (question, chunk) pairs - a stronger relevance signal than
# the independent per-chunk scores hybrid retrieval already attaches.
# It costs a local model inference pass per question (no extra Gemini
# call, no new dependency - see reranker_service.py), but still adds
# latency and a one-time model load, so it defaults OFF like the
# Sprint 6 LLM-cost features - flip it on per-deployment via .eee.

ENABLE_RERANKER = os.getenv("ENABLE_RERANKER", "False") == "True"

RERANKER_MODEL = os.getenv("RERANKER_MODEL", "BAAI/bge-reranker-base")

# When reranking is enabled, retrieve_chunks() over-fetches this many
# times the effective top-k from each source before reranking, so the
# reranker has a real candidate pool to reorder rather than just
# re-scoring an already-truncated list.
RERANKER_CANDIDATE_MULTIPLIER = int(os.getenv("RERANKER_CANDIDATE_MULTIPLIER", 3))

# Token cap passed to the cross-encoder's tokenizer (query + chunk
# combined). A real chunk (CHUNK_SIZE=800 chars, ~150-220 tokens) plus
# a typical question sits well under this, so normal reranking is
# unaffected - this exists to bound the worst case: without it, the
# model falls back to its tokenizer's own max_length (512 for
# bge-reranker-base), and one unusually long outlier chunk in the
# candidate pool drags the *entire* batch's compute up to that length
# (CrossEncoder pads every pair in a batch to the longest one present).
RERANKER_MAX_LENGTH = int(os.getenv("RERANKER_MAX_LENGTH", 320))

# Passed straight to CrossEncoder.predict(). 23 candidates (a typical
# reranker pool here) fit in one batch by default (32) - this only
# matters once RERANKER_CANDIDATE_MULTIPLIER/DYNAMIC_TOP_K_MAX push the
# pool past that.
RERANKER_BATCH_SIZE = int(os.getenv("RERANKER_BATCH_SIZE", 32))

# ==========================================
# Context Compression (Sprint 8)
# ==========================================
# Hybrid retrieval (especially with HyDE/multi-query/reranking
# enabled) can surface near-duplicate chunks - the same fact
# paraphrased, or overlapping chunks from CHUNK_OVERLAP - that pad the
# LLM's context without adding information. Compression removes
# chunks that are semantically redundant with one already kept (see
# context_compression_service.py), reusing the existing embedding
# model - no new dependency, no LLM call. Off by default: an overly
# aggressive threshold could drop a chunk that genuinely mattered, so
# this should be enabled deliberately per-deployment via .eee.

ENABLE_CONTEXT_COMPRESSION = os.getenv("ENABLE_CONTEXT_COMPRESSION", "False") == "True"

CONTEXT_COMPRESSION_THRESHOLD = float(os.getenv("CONTEXT_COMPRESSION_THRESHOLD", 0.92))

# How long (seconds) the retrieval-side caches stay warm: the full
# retrieve_chunks() result for a repeated question, the per-accessible-
# scope BM25 index, and the per-accessible-scope visible-entity set for
# graph retrieval (see retrieval_service.py / bm25_service.py /
# graph_retrieval_service.py). Short and shared across all three on
# purpose - the correctness risk they bound is the same (a document
# uploaded/embedded moments ago not showing up yet), so one knob is
# simpler than three, and short keeps that window tight.
RETRIEVAL_CACHE_TTL = int(os.getenv("RETRIEVAL_CACHE_TTL", 120))

# Defensive cap on the numbered context string sent to the LLM
# (citation_service.build_cited_context()). Not a real latency fix -
# a live benchmark during the performance audit showed even a trivial
# few-word prompt taking just as long on OpenRouter's free tier, so
# prompt size isn't the actual driver of answer latency here - this is
# a safety net for a pathological large-top_k + compression-disabled
# combination blowing up the prompt, not something normal usage hits.
MAX_CONTEXT_CHARS = int(os.getenv("MAX_CONTEXT_CHARS", 12000))

# ==========================================
# Answer Generation (Sprint 9)
# ==========================================
# Prompt templates, grounding/citation rules, and the "not found"
# fallback text live in prompt_templates.py / citation_service.py.
# ANSWER_TEMPERATURE lowers Gemini's sampling temperature below the
# provider default, so the model sticks closer to the cited sources
# instead of improvising - a direct hallucination-reduction lever.
# Applied unconditionally (not feature-flagged): it costs nothing
# extra and is a generation-quality default for this sprint, not an
# opt-in.

ANSWER_TEMPERATURE = float(os.getenv("ANSWER_TEMPERATURE", 0.2))

# Defensive cap on generated output length (not input/prompt size - see
# MAX_CONTEXT_CHARS above for why that one doesn't move the needle on
# this provider). A concise, grounded answer following the prompt's own
# "keep the answer clear and concise" rule never approaches this; it
# bounds the tail case of a rambling/looping generation, which - unlike
# prefill/TTFT - does add real wall-clock time one token at a time
# regardless of provider.
ANSWER_MAX_TOKENS = int(os.getenv("ANSWER_MAX_TOKENS", 1024))

# ==========================================
# Background Task Execution (free-tier refactor)
# ==========================================
# Document processing and AI Tasks used to require a separate Celery
# worker process talking to a Redis broker - a hard requirement most
# free-tier hosts (Render free, Railway, Fly.io free allowance,
# PythonAnywhere) don't support, since they only run a single always-on
# process. Both now dispatch onto an in-process
# concurrent.futures.ThreadPoolExecutor instead (see
# RAG/services/task_runner.py) - no broker, no second process, no new
# dependency. Django's cache (see CACHES below) also no longer has a
# Redis-backed option; LocMemCache (Django's implicit default) is the
# only cache backend now, which is fine for the short-TTL, non-critical
# caches that use it (sidebar status, BM25/graph/retrieval caches,
# geolocation, system-config sync).

BACKGROUND_WORKER_THREADS = int(os.getenv("BACKGROUND_WORKER_THREADS", 4))

# When False (default), upload_service.upload_document() processes a
# document inline, exactly as every sprint before this one. When True,
# it dispatches RAG.tasks.process_document_task onto the background
# thread pool instead and returns immediately - the request/response
# cycle no longer waits on extraction/chunking/embedding/
# graph-enrichment for large documents.
ENABLE_ASYNC_PROCESSING = os.getenv("ENABLE_ASYNC_PROCESSING", "False") == "True"

# AI Tasks (Enterprise AI Tasks module) ALWAYS dispatch to the
# background thread pool (RAG.tasks.run_ai_task) - independent of
# ENABLE_ASYNC_PROCESSING above, which only governs document upload
# processing. There is no inline/synchronous execution path for an AI
# Task run, since a run can span up to AI_TASKS_MAX_DOCUMENTS documents;
# unlike the old Celery-based design, this has no missing-worker failure
# mode, since the thread pool lives in this same process.
AI_TASKS_MAX_DOCUMENTS = int(os.getenv("AI_TASKS_MAX_DOCUMENTS", "100"))

# ==========================================
# Monitoring (Sprint 10)
# ==========================================
# Activates the logger.info()/logger.exception() calls already
# present throughout RAG/services/*.py (previously relying on
# Django's implicit default, which only surfaces WARNING+ on the root
# logger) with a consistent console format. DJANGO_LOG_LEVEL lets a
# deployment turn up verbosity without a code change.

DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        # Stamps every record with the current request's trace id (see
        # RAG.services.trace) so %(trace_id)s below lets a slow/failed
        # Ask AI request's full stage-by-stage log trail be found with
        # one grep, without touching any individual logger.info() call.
        "trace_id": {
            "()": "RAG.services.trace.TraceIdLogFilter",
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s [%(trace_id)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["trace_id"],
        },
        # Automatic, app-wide error grouping/dedup (RAG.models.ErrorGroup)
        # - additive alongside "console", not a replacement. WARNING+
        # only: every existing logger.warning()/error()/exception() call
        # across RAG/services/*.py, RAG/views.py, RAG/tasks.py starts
        # flowing into ErrorGroup with zero call-site changes. See
        # RAG.services.error_intelligence_service's module docstring.
        "error_capture": {
            "class": "RAG.services.error_intelligence_service.ErrorCaptureHandler",
            "level": "WARNING",
        },
    },
    "root": {
        "handlers": ["console", "error_capture"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console", "error_capture"],
            "level": os.getenv("DJANGO_FRAMEWORK_LOG_LEVEL", "WARNING"),
            "propagate": False,
        },
        # Chatty third-party HTTP/model-download clients that would
        # otherwise drown out RAG.* logs at INFO - each request the
        # embedding/reranker model libraries make to Hugging Face
        # logs a line by default.
        "httpx": {"level": "WARNING", "propagate": True},
        "httpcore": {"level": "WARNING", "propagate": True},
        "urllib3": {"level": "WARNING", "propagate": True},
    },
}


GEMINI_API_KEY = env(
    "GEMINI_API_KEY",
    default=""
)

# LLM provider selection.
#
# OpenRouter is the default primary provider (a free-tier model) so
# everyday usage doesn't run into Gemini's free-tier quota limits.
# set LLM_PROVIDER=gemini in .eee to flip which one is primary.
LLM_PROVIDER = env("LLM_PROVIDER", default="openrouter")

# Whether llm_client.LLMClient is allowed to fall through to another
# configured provider when the primary one fails/times out/rate-limits.
# Defaults OFF: a provider selected in Settings must be the one that
# actually answers, or the request fails with a clear error - never a
# silent, invisible switch to a different provider/model. An admin who
# wants resilience over strict provider fidelity can flip this on from
# Admin > Settings (SystemConfiguration.enable_fallback overrides this
# at runtime, same pattern as every other MANAGED_SETTINGS_FIELDS entry).
LLM_FALLBACK_ENABLED = env.bool("LLM_FALLBACK_ENABLED", default=False)

# Gemini's own model name - kept independent from OPENROUTER_MODEL so
# the Gemini fallback client never gets handed an OpenRouter-style
# model string (e.g. "deepseek/deepseek-chat-v3.1:free").
LLM_MODEL = env("LLM_MODEL", default="gemini-2.0-flash")

OPENROUTER_API_KEY = env("OPENROUTER_API_KEY", default="")

# Was "deepseek/deepseek-chat-v3.1:free", then "openai/gpt-oss-20b:free" -
# both specific free slugs have since been retired by OpenRouter
# (live-verified: each now 404s with "This model is unavailable for
# free. The paid version is available now - use this slug instead:
# <same slug without ':free'>"). Free-tier model availability shifts
# over time; nvidia/nemotron-3-super-120b-a12b:free is live-verified
# working (both plain and JSON-mode generation) as of this fix, and -
# like the other two providers' models - changeable from Admin >
# Settings without a redeploy if it's ever retired too. See
# RAG.services.llm_client.PROVIDER_REGISTRY.
OPENROUTER_MODEL = env(
    "OPENROUTER_MODEL",
    default="nvidia/nemotron-3-super-120b-a12b:free"
)

# Groq - OpenAI-compatible REST API, no SDK dependency (see
# RAG.services.llm_client.GroqClient). llama-3.1-8b-instant is a
# long-standing, small/fast free-tier Groq model - a reasonable
# default; changeable from Admin > Settings like the other two.
GROQ_API_KEY = env("GROQ_API_KEY", default="")
GROQ_MODEL = env("GROQ_MODEL", default="llama-3.1-8b-instant")

# Per-attempt request timeout and per-provider retry count for the LLM
# fallback chain (RAG.services.llm_client.LLMClient) - infra-level
# knobs, env-only (not exposed in Admin > Settings, unlike the
# provider/model choices). Deliberately short: the whole point of the
# fallback chain is to fail fast and move to the next provider rather
# than hang on a slow one.
LLM_REQUEST_TIMEOUT = env.int("LLM_REQUEST_TIMEOUT", default=30)
LLM_MAX_RETRIES = env.int("LLM_MAX_RETRIES", default=1)

SITE_URL = env("SITE_URL", default="")
SITE_NAME = env("SITE_NAME", default="Cortex")

# Email (auth/notification system) - no email infrastructure existed
# in this project before. Backend choice is driven by whether real SMTP
# creds are actually present in .eee, not by DEBUG - a DEBUG=True local
# dev setup should still send real mail once EMAIL_HOST is filled in
# (that's the whole point of adding credentials), and DEBUG=False with
# no EMAIL_HOST would otherwise try to connect to a blank host and
# fail outright. Console backend (prints to the server log) is purely
# the zero-setup fallback for "no credentials configured yet".
# RAG.services.email_service is the only place that should ever call
# django.core.mail directly.
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if env("EMAIL_HOST", default="")
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=f"{SITE_NAME} <no-reply@example.com>")

# "Remember Me" on login - request.session.set_expiry() is set to this
# (persistent cookie) when checked, or explicitly to 0 (browser-close)
# when not - see RAG.auth_views.login_user.
REMEMBER_ME_SESSION_AGE = env.int("REMEMBER_ME_SESSION_AGE", default=60 * 60 * 24 * 30)  # 30 days

# Plain-HTTP localhost SPA talking *directly* to Django (no Vite proxy):
#   http://localhost:5173  →  http://localhost:8000/api/...
# Use the same hostname on both sides (localhost vs localhost). Mixing
# localhost and 127.0.0.1 is cross-site and SameSite=Lax drops sessionid.
# HttpOnly session + CSRF cookies; CSRF value also returned by
# GET /api/auth/session/. Skip on PaaS hosts that terminate HTTPS.
_on_paas = bool(
    _railway_public_domain
    or os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
)
if not _on_paas:
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_DOMAIN = None

    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_DOMAIN = None

    SECURE_SSL_REDIRECT = False
