# Generated by Django 6.0.7 on 2026-07-30 14:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0002_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
