# Generated by Django 6.0.7 on 2026-07-30 14:22

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0003_documentchunk_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['chunk_number']},
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='RAG.documentchunk')),
            ],
        ),
    ]
