# Generated by Django 6.0.7 on 2026-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0004_alter_documentchunk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
