# Generated by Django 6.0.7 on 2026-07-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0005_document_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
