# Generated by Django 6.0.7 on 2026-07-31 15:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0006_document_chunk_count_document_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
