# Generated by Django 6.0.7 on 2026-08-04 17:25

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0009_entity_entitymention_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
