# Generated by Django 6.0.6 on 2026-08-05 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0012_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_provider', models.CharField(choices=[('gemini', 'Gemini'), ('openrouter', 'OpenRouter')], default='openrouter', max_length=20)),
                ('top_k', models.PositiveSmallIntegerField(default=3)),
                ('answer_temperature', models.FloatField(default=0.2)),
                ('chunk_size', models.PositiveIntegerField(default=800, help_text="Applies to newly-uploaded documents only - existing chunks aren't retroactively resized.")),
                ('chunk_overlap', models.PositiveIntegerField(default=150)),
                ('enable_query_expansion', models.BooleanField(default=False)),
                ('enable_hyde', models.BooleanField(default=False)),
                ('enable_multi_query', models.BooleanField(default=False)),
                ('multi_query_variants', models.PositiveSmallIntegerField(default=3)),
                ('enable_dynamic_top_k', models.BooleanField(default=True)),
                ('dynamic_top_k_max', models.PositiveSmallIntegerField(default=10)),
                ('enable_reranker', models.BooleanField(default=False)),
                ('reranker_candidate_multiplier', models.PositiveSmallIntegerField(default=3)),
                ('enable_context_compression', models.BooleanField(default=False)),
                ('context_compression_threshold', models.FloatField(default=0.92)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
            },
        ),
    ]
