# Generated by Django 6.0.6 on 2026-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0013_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Set by upload_service.process_uploaded_document() - PENDING until the Embed button is clicked (documents_view.document_embed).', max_length=20),
        ),
    ]
