# Generated by Django 6.0.6 on 2026-08-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0016_remove_super_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Built-in role (admin/user) seeded by seed_rbac - not meant to be deleted.'),
        ),
    ]
