# Generated by Django 6.0.6 on 2026-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0018_remove_dashboard_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Pinned for follow-up in Admin > Queries. A shared review flag, not tied to any one admin.'),
        ),
    ]
