# Generated by Django 6.0.6 on 2026-08-07 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0020_document_archived_at_document_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('analyze', 'Analyze Documents'), ('compare', 'Compare Documents'), ('summarize', 'Summarize Documents'), ('extract', 'Extract Information'), ('validate', 'Validate Against Reference Documents'), ('find_similar', 'Find Similar Documents'), ('organize', 'Organize Documents'), ('report', 'Generate Reports')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Task-specific options from the Configure step (criteria, fields, similarity_threshold, ...) - shape depends on task_type, validated by ai_tasks_engine_service, not the DB.')),
                ('document_count', models.PositiveIntegerField(default=0, help_text='Snapshot of the target-document count at creation time, after the AI_TASKS_MAX_DOCUMENTS cap was enforced.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_task_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Display order within its group - Analyze ranking, Organize group index, Find Similar cluster index. NULL where no ordering applies.', null=True)),
                ('score', models.FloatField(blank=True, help_text='Task-specific numeric score - Analyze relevance, Validate compliance percent, Find Similar similarity. NULL where not applicable.', null=True)),
                ('title', models.CharField(blank=True, default='', help_text="Document title snapshot for a per-document row, or a heading (e.g. 'Executive Summary') for a corpus-level row.", max_length=255)),
                ('summary', models.TextField(blank=True, default='', help_text='LLM prose finding for this result, with inline [n] citation markers per the citation_service.py convention.')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Task-specific structured payload (extracted fields, violations, combined table, report sections, ...). Rendered generically by templates/ai_tasks/_result_row.html based on which keys are present.')),
                ('citations', models.JSONField(blank=True, default=list, help_text="[{number, document, chunk_number, role}, ...] - the subset of build_cited_context() source blocks this result's summary actually cited.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_task_results', to='RAG.document')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='RAG.aitaskrun')),
            ],
            options={
                'ordering': ['run_id', 'rank', '-score', 'id'],
                'indexes': [models.Index(fields=['run', 'document'], name='RAG_aitaskr_run_id_a271d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AITaskRunDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('target', 'Target'), ('reference', 'Reference')], default='target', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_task_run_memberships', to='RAG.document')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_documents', to='RAG.aitaskrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'role'], name='RAG_aitaskr_run_id_ffa495_idx')],
                'unique_together': {('run', 'document')},
            },
        ),
    ]
