# Generated by Django 6.0.6 on 2026-08-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0021_aitaskrun_aitaskresult_aitaskrundocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='gemini_model',
            field=models.CharField(default='gemini-2.0-flash', max_length=150),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='groq_model',
            field=models.CharField(default='llama-3.1-8b-instant', max_length=150),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='openrouter_model',
            field=models.CharField(default='openai/gpt-oss-20b:free', max_length=150),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='llm_provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('gemini', 'Gemini')], default='openrouter', max_length=20),
        ),
    ]
