# Generated by Django 6.0.6 on 2026-08-07 20:11

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0022_systemconfiguration_gemini_model_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chunkembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunkembedding_embedding_hnsw', opclasses=['vector_l2_ops']),
        ),
    ]
