# Generated by Django 6.0.6 on 2026-08-08 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0023_chunkembedding_chunkembedding_embedding_hnsw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('source', models.CharField(choices=[('ask_ai', 'Ask AI'), ('ai_task', 'AI Task')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('providers_attempted', models.JSONField(blank=True, default=list, help_text='Ordered list of provider keys actually tried this request/run - len() > 1 means a fallback happened.')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('llm_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('time_to_first_token_ms', models.PositiveIntegerField(blank=True, help_text='Only populated for a streamed Ask AI answer.', null=True)),
                ('retrieved_chunks', models.PositiveIntegerField(default=0)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('cache_hit', models.BooleanField(blank=True, null=True)),
                ('stages', models.JSONField(blank=True, default=list, help_text='[{name, duration_ms, ...context}, ...] in execution order - the same shape perf.timed_stage() already logs to console.')),
                ('total_duration_ms', models.PositiveIntegerField(default=0)),
                ('bottleneck_stage', models.CharField(blank=True, default='', max_length=100)),
                ('bottleneck_label', models.CharField(blank=True, default='', max_length=200)),
                ('error_type', models.CharField(blank=True, default='', help_text='A short classified code (e.g. LLMTimeoutError, AllProvidersFailedError) - never a raw exception message.', max_length=100)),
                ('error_message', models.TextField(blank=True, default='', help_text='Sanitized short message for support/debugging - must never contain API keys, tokens, or a raw stack trace.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ai_task_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace', to='RAG.aitaskrun')),
                ('query_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace', to='RAG.querylog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='RAG_aireque_source_dbb9b5_idx'), models.Index(fields=['created_at'], name='RAG_aireque_created_9f942d_idx')],
            },
        ),
    ]
