# Generated by Django 6.0.6 on 2026-08-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0024_airequesttrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='sha256(logger_name:level:error_type-or-normalized-message) - what groups occurrences together.', max_length=64, unique=True)),
                ('logger_name', models.CharField(db_index=True, help_text='e.g. "RAG.services.llm_client", "django.request".', max_length=200)),
                ('level', models.CharField(db_index=True, help_text='WARNING / ERROR / CRITICAL - matches the Python logging level name.', max_length=20)),
                ('error_type', models.CharField(blank=True, default='', help_text='Exception class name, if the log call included exc_info - blank for a plain logger.warning() with no exception.', max_length=200)),
                ('message', models.TextField(help_text="Redacted (see error_intelligence_service.redact_secrets()), truncated first-occurrence message - not a full traceback, by design (see the module docstring on what this deliberately doesn't store).")),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('recent_occurrences', models.JSONField(blank=True, default=list, help_text="[{trace_id, timestamp}, ...] - the most recent occurrences only (capped), for correlating back to an AIRequestTrace or a specific request via RAG.services.trace's trace_id / the X-Request-ID response header.")),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['level', 'last_seen'], name='RAG_errorgr_level_ccab8e_idx'), models.Index(fields=['logger_name', 'last_seen'], name='RAG_errorgr_logger__7d8054_idx')],
            },
        ),
    ]
