# Generated by Django 6.0.6 on 2026-08-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0025_errorgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP of the request that triggered this event, via activity_log_service.get_client_ip() - None for system-initiated events with no request in scope.', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
