# Generated by Django 6.0.6 on 2026-08-09 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0026_activitylog_city_activitylog_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='Raw User-Agent header of the triggering request - parsed on read by RAG.services.device_intelligence_service.parse_device() into device type/browser/OS for login history, never parsed at write time so a parser change never needs a backfill.'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('headline', models.CharField(blank=True, default='', help_text='One-line professional tagline, e.g. "AI Engineer | RAG Systems | Knowledge Intelligence".', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('job_title', models.CharField(blank=True, default='', max_length=150)),
                ('employee_id', models.CharField(blank=True, default='', help_text='Informational only - not DB-unique, since nothing else in this project validates or looks up users by it yet.', max_length=50)),
                ('team', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', help_text='Self-reported office/city location - distinct from the IP-derived login location on ActivityLog.', max_length=150)),
                ('timezone', models.CharField(blank=True, default='', help_text="IANA name (e.g. 'America/New_York') - free-form so any valid value saves even if the UI's curated <select> list doesn't cover it.", max_length=50)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of plain strings.')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of plain strings.')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('team', 'Team'), ('private', 'Private')], default='private', help_text='Stored preference only - there is no peer-facing profile viewing page yet to enforce it against; Admin views always see the full profile regardless (existing RBAC bypass pattern, e.g. Role.has_permission).', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
