# Generated by Django 6.0.6 on 2026-08-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0027_activitylog_user_agent_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text="Non-plain-text answer extras at the time this question was asked - {'key_points': [...], 'table': {...} or None}. Persisted so replaying a question from Search History (RAG.views.ask_ai's ?log_id= path) can show the same structured findings the live answer did, instead of just the answer text. A streamed answer (RAG.views.ask_ai_stream) always writes {'key_points': [], 'table': None} here since it's plain text."),
        ),
        migrations.AlterField(
            model_name='aitaskresult',
            name='score',
            field=models.FloatField(blank=True, help_text='Task-specific numeric score on a consistent 0-100 scale - Analyze relevance, Validate compliance percent, Find Similar/Organize similarity (cosine similarity * 100). NULL where not applicable.', null=True),
        ),
    ]
