# Generated by Django 6.0.6 on 2026-08-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0028_querylog_structured_data_alter_aitaskresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitaskrun',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text="Set by ai_task_cancel() when a user stops a pending/running run. execute_run() checks this in _call_llm_json() (the one choke point every task handler's LLM calls go through) between calls and unwinds to status=CANCELLED - so a stop takes effect within one LLM call's worth of latency, not instantly, and never mid-write of a result row."),
        ),
        migrations.AddField(
            model_name='aitaskrun',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', help_text="The AsyncResult id from run_ai_task.delay() - lets ai_task_cancel() best-effort revoke() a still-queued task via Celery. A running task's actual stop mechanism is cooperative (cancel_requested below, checked in _call_llm_json()), not this id - Celery revoke(terminate=True) needs a prefork worker pool, which isn't available on every deployment (e.g. Windows workers typically run --pool=solo/threads).", max_length=255),
        ),
        migrations.AlterField(
            model_name='aitaskrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
