# Generated by Django 6.0.6 on 2026-08-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0029_aitaskrun_cancel_requested_aitaskrun_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequesttrace',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=20),
        ),
    ]
