# Generated by Django 6.0.6 on 2026-08-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0030_alter_airequesttrace_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitaskrun',
            name='celery_task_id',
        ),
    ]
