# Generated by Django 6.0.6 on 2026-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0031_remove_aitaskrun_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
