# Generated by Django 6.0.6 on 2026-08-11 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0032_systemconfiguration_enable_fallback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True once the account holder has completed email OTP verification at signup (see RAG.services.otp_service). Pre-existing accounts were backfilled to True by a one-time data migration when this field was added - only new signups actually go through OTP.'),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_email_categories', models.JSONField(blank=True, default=list, help_text='Category namespaces (e.g. "document", "ai_task") the user has opted out of *email* delivery for.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('signup', 'Signup Verification')], default='signup', max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Incremented on every failed verify attempt against this row - a durable, per-row cap (RAG.services.otp_service.MAX_OTP_ATTEMPTS) on top of the cache-based cross-row rate limit in rate_limit_service.')),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used', '-created_at'], name='RAG_emailot_user_id_43dfdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra structured payload for the event, e.g. {"document_id": 12, "share_id": 7}.')),
                ('action_url', models.CharField(blank=True, default='', help_text='Where the "Open" action navigates, e.g. a document URL. Computed at creation time via reverse() - never trusted as an authorization check by itself, the target view re-validates access.', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.CharField(blank=True, default='', help_text="Sanitized failure reason only (exception class name, not a raw traceback) - mirrors ErrorGroup's no-raw-stack-trace contract.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who caused this notification, if a specific user did (e.g. who shared the document). Blank for system-generated events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='RAG_notific_recipie_0a57c1_idx')],
            },
        ),
    ]
