# Generated by Django 6.0.6 on 2026-08-11 14:16

from django.db import migrations


def backfill_email_verified(apps, schema_editor):
    """
    Grandfathers every account that existed before email OTP
    verification was introduced - only new signups (created after this
    migration runs) go through OTP and start at email_verified=False.
    Uses the historical model (apps.get_model), the standard-safe data
    migration pattern, not the "live" RAG.models.UserProfile.
    """

    UserProfile = apps.get_model("RAG", "UserProfile")
    UserProfile.objects.update(email_verified=True)


def noop_reverse(apps, schema_editor):
    """Deliberately a no-op, not "set email_verified=False for everyone" - reversing this migration should not retroactively lock out every existing account."""


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0033_userprofile_email_verified_notificationpreference_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_email_verified, noop_reverse),
    ]
