# Generated by Django 6.0.6 on 2026-08-11 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0034_backfill_email_verified_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentshare',
            name='documentshare_exactly_one_target',
        ),
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together={('document', 'shared_with_role'), ('document', 'shared_with_user')},
        ),
        migrations.AddField(
            model_name='documentshare',
            name='invited_email',
            field=models.CharField(blank=True, default='', help_text='Set only while pending - an email with no matching account yet. Cleared (and shared_with_user set) once that address completes signup + OTP verification.', max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together={('document', 'invited_email'), ('document', 'shared_with_role'), ('document', 'shared_with_user')},
        ),
        migrations.AddConstraint(
            model_name='documentshare',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invited_email', ''), ('shared_with_role__isnull', True), ('shared_with_user__isnull', False)), models.Q(('invited_email', ''), ('shared_with_role__isnull', False), ('shared_with_user__isnull', True)), models.Q(('invited_email__gt', ''), ('shared_with_role__isnull', True), ('shared_with_user__isnull', True)), _connector='OR'), name='documentshare_exactly_one_target'),
        ),
    ]
