# Generated by Django 6.0.6 on 2026-08-11 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0035_remove_documentshare_documentshare_exactly_one_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together={('document', 'shared_with_role'), ('document', 'shared_with_user')},
        ),
        migrations.AddConstraint(
            model_name='documentshare',
            constraint=models.UniqueConstraint(condition=models.Q(('invited_email__gt', '')), fields=('document', 'invited_email'), name='documentshare_unique_pending_invite'),
        ),
    ]
