# Generated by Django 6.0.6 on 2026-08-18 14:14
#
# `processing_attempts`, `processing_error`, `processing_started_at`, and
# `processing_completed_at` already exist as live columns on RAG_document in
# some environments (added directly against the database, outside any
# migration - processing_attempts/processing_error are NOT NULL with no
# server-side default, which is what produced the IntegrityError on
# /documents/ uploads: Document.objects.create() never supplied them).
#
# The database operations below use raw SQL with IF NOT EXISTS / guarded
# UPDATEs so this migration is safe to apply both here (columns already
# present) and on a fresh database (columns absent, created from scratch).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0036_alter_documentshare_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='document',
                    name='processing_attempts',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='document',
                    name='processing_completed_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='document',
                    name='processing_error',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='document',
                    name='processing_started_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE "RAG_document" ADD COLUMN IF NOT EXISTS '
                        '"processing_attempts" integer NOT NULL DEFAULT 0;',
                        'ALTER TABLE "RAG_document" ALTER COLUMN '
                        '"processing_attempts" SET DEFAULT 0;',
                        'UPDATE "RAG_document" SET processing_attempts = 0 '
                        'WHERE processing_attempts IS NULL;',

                        'ALTER TABLE "RAG_document" ADD COLUMN IF NOT EXISTS '
                        '"processing_error" text NOT NULL DEFAULT \'\';',
                        'ALTER TABLE "RAG_document" ALTER COLUMN '
                        '"processing_error" SET DEFAULT \'\';',
                        'UPDATE "RAG_document" SET processing_error = \'\' '
                        'WHERE processing_error IS NULL;',

                        'ALTER TABLE "RAG_document" ADD COLUMN IF NOT EXISTS '
                        '"processing_started_at" timestamp with time zone NULL;',

                        'ALTER TABLE "RAG_document" ADD COLUMN IF NOT EXISTS '
                        '"processing_completed_at" timestamp with time zone NULL;',
                    ],
                    reverse_sql=[
                        'ALTER TABLE "RAG_document" DROP COLUMN IF EXISTS '
                        '"processing_completed_at";',
                        'ALTER TABLE "RAG_document" DROP COLUMN IF EXISTS '
                        '"processing_started_at";',
                        'ALTER TABLE "RAG_document" DROP COLUMN IF EXISTS '
                        '"processing_error";',
                        'ALTER TABLE "RAG_document" DROP COLUMN IF EXISTS '
                        '"processing_attempts";',
                    ],
                ),
            ],
        ),
    ]
