# Generated by Django 6.0.6 on 2026-08-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0037_add_document_processing_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='openrouter_model',
            field=models.CharField(default='nvidia/nemotron-3-super-120b-a12b:free', max_length=150),
        ),
    ]
