# Generated by Django 6.0.6 on 2026-09-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0039_organizationtype_organization_organizationmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="NULL means this document lives in its owner's Personal Workspace - today's exact pre-multi-tenancy behavior, unchanged. Set only when created while an organization workspace was active; every org-scoped query filters by this field, never by `user` alone, for a document that has it set. CASCADE: deleting an organization deletes its documents, matching how deleting a Document's owning User already cascades to it - a tenant's data doesn't outlive the tenant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='RAG.organization'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_org_library',
            field=models.BooleanField(db_index=True, default=False, help_text="Admin-managed Organization Library membership - visible/retrievable to every user, not just the owner. See document_access_service. Not related to the `organization` field below despite the name overlap - this predates multi-tenancy and means 'shared workspace-wide', while `organization` means 'belongs to this one tenant'. Kept as-is rather than renamed for now; see the Organization model's docstring."),
        ),
    ]
