# Generated by Django 6.0.6 on 2026-09-02 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0041_organizationauditlog_organizationinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aitaskrun',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="NULL means this run was started in the user's Personal Workspace - see Document.organization's help_text for the shared convention.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_task_runs', to='RAG.organization'),
        ),
        migrations.AddField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="NULL means this entity was extracted from a Personal Workspace document - see Document.organization's help_text for the shared convention.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='RAG.organization'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="NULL means this question was asked in the user's Personal Workspace - see Document.organization's help_text for the shared convention every organization-aware model in this file follows.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='RAG.organization'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="NULL means this relationship was extracted from a Personal Workspace document - see Document.organization's help_text for the shared convention.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='RAG.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('user', 'organization', 'name', 'entity_type')},
        ),
    ]
