# Generated by Django 6.0.6 on 2026-09-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0042_alter_entity_unique_together_aitaskrun_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], default='', help_text='Self-reported company size band, collected during company signup - purely informational, no behavior branches on it.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', help_text="Decided once, during signup (or by accepting an organization invitation), never by a workspace switcher - see auth_views.signup()/org_invitation_service.accept_invitation(). A PERSONAL account never holds an OrganizationMembership; a COMPANY account's requests are always scoped to one of its organizations, never to Personal Workspace - org_permission_service.resolve_request_organization() enforces both directions server-side, so this field (not any frontend state) is the actual source of truth an authorization decision reads from.", max_length=10),
        ),
    ]
