# Generated by Django 6.0.6 on 2026-09-04 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0044_backfill_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='RAG.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='NULL = a top-level department. Must belong to the same organization as this department - enforced in department_service.py, not here.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='RAG.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='RAG.department')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='RAG.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text="A document can belong to several departments (e.g. a cross-department policy) - purely a narrowing filter on top of organization scope, never a widening one: a department a viewer can't see never grants access to a document their organization membership wouldn't already allow.", related_name='documents', through='RAG.DepartmentDocument', to='RAG.department'),
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('department_manager', 'Department Manager'), ('member', 'Member')], default='member', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='RAG.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'parent'], name='RAG_departm_organiz_2212c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='departmentdocument',
            index=models.Index(fields=['document'], name='RAG_departm_documen_6f29f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentdocument',
            unique_together={('department', 'document')},
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['user'], name='RAG_departm_user_id_03cd89_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['department', 'role'], name='RAG_departm_departm_89f4aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentmembership',
            unique_together={('department', 'user')},
        ),
    ]
