# Generated by Django 6.0.6 on 2026-09-04 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0045_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('max_queries_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ai_task_runs_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_storage_bytes', models.BigIntegerField(blank=True, null=True)),
                ('max_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivating hides a Plan from future assignment without deleting it - existing Subscriptions referencing it (PROTECT below) keep working.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='aitaskrun',
            index=models.Index(fields=['organization', 'created_at'], name='RAG_aitaskr_organiz_fd8d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['organization', 'created_at'], name='RAG_querylo_organiz_21aa95_idx'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='RAG.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='RAG.plan'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'current_period_end'], name='RAG_subscri_organiz_dd0df1_idx'),
        ),
    ]
