# Generated by Django 6.0.6 on 2026-09-05 20:23
#
# 2026-09-06 product decision: organization roles collapsed from four
# tiers (Owner/Admin/Manager/Member) to two (Owner/Member). Every
# existing 'org_admin'/'manager' row is data-migrated down to 'member'
# BEFORE the schema's choices are narrowed - Django doesn't enforce
# `choices` at the database level, so the AlterField above wouldn't by
# itself refuse or crash on a row still holding a retired value, but
# leaving one behind would silently violate the new invariant this
# whole feature exists to establish (see OrganizationMembership's
# docstring). The reverse migration is a deliberate no-op: there is no
# way to recover which specific rows were originally Admin vs. Manager
# once collapsed, so un-collapsing isn't offered - rolling back this
# migration undoes the schema change only, not the data change.

from django.db import migrations, models

_RETIRED_ADMIN = "org_admin"
_RETIRED_MANAGER = "manager"
_MEMBER = "member"


def collapse_retired_roles_to_member(apps, schema_editor):
    OrganizationMembership = apps.get_model("RAG", "OrganizationMembership")
    OrganizationInvitation = apps.get_model("RAG", "OrganizationInvitation")

    OrganizationMembership.objects.filter(role__in=[_RETIRED_ADMIN, _RETIRED_MANAGER]).update(role=_MEMBER)
    # Pending invitations offering a retired role are rewritten the
    # same way, so accepting one later can't hand out a role that no
    # longer exists - already-ACCEPTED/EXPIRED/REVOKED rows are
    # historical record and are included too for consistency, since
    # they're never re-read for authorization, only for display.
    OrganizationInvitation.objects.filter(role__in=[_RETIRED_ADMIN, _RETIRED_MANAGER]).update(role=_MEMBER)


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0046_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Set when org_member_registration_service.register_company_member() creates or reactivates a company-registered member's account with a system-generated password (see that module for the full flow) - never set for a self-service Personal/Company signup, which chooses its own password up front. RAG.api.auth_views.login_view() reports this in the session payload; the SPA blocks every route except the forced password-change page until it's cleared."),
        ),
        migrations.RunPython(collapse_retired_roles_to_member, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(choices=[('org_owner', 'Owner'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('org_owner', 'Owner'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
