# Generated by Django 6.0.6 on 2026-09-05 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0047_collapse_org_roles_and_forced_password_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_credits_balance',
            field=models.PositiveIntegerField(default=0, help_text="A spendable AI usage balance, independent of (and in addition to) the Plan's monthly max_queries_per_month/max_ai_task_runs_per_month caps - see billing_service.check_ai_credits()/deduct_ai_credits(). Only an Owner can add credits (billing_service.add_ai_credits()); every addition/deduction is recorded in AICreditTransaction below, never inferred from this running total alone."),
        ),
        migrations.CreateModel(
            name='AICreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for a top-up, negative for a spend.')),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(help_text='e.g. "Question asked", "AI Task run", "Credits added by Owner".', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_transactions', to='RAG.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
