# Generated by Django 6.0.6 on 2026-09-05 22:56
#
# 0048 backfilled every existing Organization row's new ai_credits_balance
# column to the literal integer 0 (AddField's own default-backfill
# behavior) - that's indistinguishable from "activated, then spent down
# to zero" unless corrected here. This migration's data step resets
# every row still sitting at that untouched backfilled 0 to NULL
# (unlimited) before the schema's own default changes - an org that
# never asked for credit metering must never look identical to one
# that's genuinely run out.

from django.db import migrations, models


def reset_untouched_zero_balances_to_null(apps, schema_editor):
    Organization = apps.get_model("RAG", "Organization")
    Organization.objects.filter(ai_credits_balance=0).update(ai_credits_balance=None)


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0048_ai_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ai_credits_balance',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="A spendable AI usage balance, independent of (and in addition to) the Plan's monthly max_queries_per_month/max_ai_task_runs_per_month caps - see billing_service.check_ai_credits()/deduct_ai_credits(). NULL (every organization's default, until an Owner ever tops up) means unlimited, the same 'absence means today's behavior, nothing breaks until someone opts in' convention Subscription's own absence already means for the Plan-based caps - a brand-new organization must never be silently blocked from AI features it never asked to meter. Only an Owner can add credits (billing_service.add_ai_credits()), which is the one place this ever becomes a real (non-NULL) number; every addition/deduction from that point on is recorded in AICreditTransaction below, never inferred from this running total alone.", null=True),
        ),
        migrations.RunPython(reset_untouched_zero_balances_to_null, migrations.RunPython.noop),
    ]
