# Generated by Django 6.0.6 on 2026-09-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0049_ai_credits_null_means_unlimited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequesttrace',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Denormalized from query_log.organization / ai_task_run.organization at write time (observability_service.save_trace()) for cheap per-company/system-wide AI usage aggregation - NULL means Personal Workspace, same convention as Document.organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_traces', to='RAG.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='disabled_features',
            field=models.JSONField(blank=True, default=list, help_text="Feature codes (RAG.models.FEATURE_CODES) this specific member is blocked from, even though the organization's Plan includes them - Owner-only, set via org_member_feature_service.set_member_disabled_features(). Empty = no member-specific restriction, the same absence-means-allowed convention Plan.included_features and Subscription's own absence both use. Never applies to an Owner (see set_member_disabled_features()'s guard)."),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_features',
            field=models.JSONField(blank=True, default=list, help_text="Feature codes (FEATURE_CODES) this Plan grants. Empty list = every feature included (unrestricted) - same 'absence means unlimited' convention as max_queries_per_month=None, so every Plan created before this field existed keeps granting full access with zero admin action required."),
        ),
        migrations.AddIndex(
            model_name='airequesttrace',
            index=models.Index(fields=['organization', 'created_at'], name='RAG_aireque_organiz_ff2207_idx'),
        ),
    ]
