# Generated by Django 6.0.6 on 2026-09-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0051_backfill_airequesttrace_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='RAG_departm_organiz_2212c1_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='departments',
        ),
        migrations.AlterUniqueTogether(
            name='departmentdocument',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='departmentdocument',
            name='RAG_departm_documen_6f29f9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='departmentmembership',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='departmentmembership',
            name='RAG_departm_user_id_03cd89_idx',
        ),
        migrations.RemoveIndex(
            model_name='departmentmembership',
            name='RAG_departm_departm_89f4aa_idx',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='departmentmembership',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='departmentmembership',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='DepartmentDocument',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DepartmentMembership',
        ),
    ]
