# Generated by Django 6.0.6 on 2026-09-07 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0052_alter_department_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['plan_type', 'name']},
        ),
        migrations.AddField(
            model_name='aicredittransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_ai_credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_credit_purchase',
            field=models.BooleanField(default=True, help_text='Whether an Owner/Personal user on this Plan may buy extra credits as an add-on (billing_service.add_ai_credits()/add_personal_ai_credits()) on top of included_credits.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_credits',
            field=models.PositiveIntegerField(default=0, help_text='AI credits this Plan grants each billing period - refilled to this exact amount on every period rollover (see billing_service._advance_period()), not accumulated. 0 = this Plan includes no credits.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('company', 'Company'), ('personal', 'Personal')], default='company', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="NULL or 0 = free plan. Internal bookkeeping only - no real payment processor charges this (see billing_service.py's module docstring).", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_credits_balance',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Personal-Workspace mirror of Organization.ai_credits_balance - a completely separate credit pool, never shared with any Company workspace this same user might also belong to. NULL = never topped up / no Personal Plan assigned yet (unlimited, same 'absence means unlimited' convention).", null=True),
        ),
        migrations.AlterField(
            model_name='aicredittransaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_transactions', to='RAG.organization'),
        ),
        migrations.AlterField(
            model_name='aicredittransaction',
            name='reason',
            field=models.CharField(help_text='e.g. "Question asked", "AI Task run", "Credits added by Owner", "Plan period refill".', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='RAG.organization'),
        ),
        migrations.AddConstraint(
            model_name='aicredittransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('user__isnull', True)), models.Q(('organization__isnull', True), ('user__isnull', False)), _connector='OR'), name='ai_credit_transaction_exactly_one_of_organization_or_user'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('user__isnull', True)), models.Q(('organization__isnull', True), ('user__isnull', False)), _connector='OR'), name='subscription_exactly_one_of_organization_or_user'),
        ),
        migrations.AddField(
            model_name='planchangerequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_requests', to='RAG.organization'),
        ),
        migrations.AddField(
            model_name='planchangerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planchangerequest',
            name='requested_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='RAG.plan'),
        ),
        migrations.AddField(
            model_name='planchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planchangerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_plan_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['status', 'created_at'], name='RAG_plancha_status_f748cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='planchangerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('user__isnull', True)), models.Q(('organization__isnull', True), ('user__isnull', False)), _connector='OR'), name='plan_request_exactly_one_of_organization_or_user'),
        ),
    ]
