# Generated by Django 6.0.6 on 2026-09-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0053_planchangerequest_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='max_ai_task_runs_per_month',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Same per-member sub-quota as max_queries_per_month above, counted against AITaskRun rows instead and enforced by billing_service.check_member_ai_task_limit().', null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='max_queries_per_month',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Owner-set sub-quota on how many questions THIS member may ask per billing period - a SEPARATE, count-based ceiling from the organization's own AI credit balance (Organization.ai_credits_balance, the org-wide spend-metering currency), enforced independently of it. Always bounded by (never exceeding) the org's active Plan's own max_queries_per_month when one is set - see org_member_limits_service.set_member_usage_limits()'s validation. NULL (default) means no member-specific cap, the same absence-means-unrestricted convention disabled_features above already uses. Counted against QueryLog rows scoped to this user (billing_service.get_member_usage()) and enforced as a hard block by billing_service.check_member_query_limit(). Never applies to an Owner (see set_member_usage_limits()'s guard).", null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ai_credits_balance',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="A spendable AI usage balance - the organization's SOLE spend-metering currency (see billing_service.py's module docstring); the Plan's own max_queries_per_month/max_ai_task_runs_per_month are informational quota display only, not a second enforcement gate. See billing_service.check_ai_credits()/deduct_ai_credits(). NULL (every organization's default, until an Owner ever tops up) means unlimited, the same 'absence means today's behavior, nothing breaks until someone opts in' convention Subscription's own absence already means for the Plan-based caps - a brand-new organization must never be silently blocked from AI features it never asked to meter. Only an Owner can add credits (billing_service.add_ai_credits()), which is the one place this ever becomes a real (non-NULL) number; every addition/deduction from that point on is recorded in AICreditTransaction below, never inferred from this running total alone.", null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='allow_credit_purchase',
            field=models.BooleanField(default=True, help_text='Whether an Owner on this Plan may buy extra credits as an add-on (billing_service.add_ai_credits()) on top of included_credits.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_ai_task_runs_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Same informational-only role as max_queries_per_month above, for AI Task runs.', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_queries_per_month',
            field=models.PositiveIntegerField(blank=True, help_text="Informational monthly quota, shown alongside usage for reference - NOT an independent enforcement gate. AI credits (included_credits below) are the organization's sole spend-metering currency (see billing_service.py's module docstring for why these two axes were merged into one); an Owner can still narrow an individual member below whatever this number implies via OrganizationMembership.max_queries_per_month, which IS a real hard block.", null=True),
        ),
    ]
